#!/usr/bin/env bash
# Printing "Best School" 10 times and on the 9th iteration also print "Hi" 
i=0
while [ $i -le 10 ];
do
    echo "Best School";
    if [ $i -eq 9 ]
    then
        echo "Hi";
    fi
    i=`expr $i + 1`;
done
