#!/usr/bin/env bash
# printing numbers 1-20 except on 4th, 9th and 17th iterations 

i=1
while [ $i -le 20 ]
do
    case $i in

    4)
        echo $i
        echo 'bad luck from China'
        ;;

    6)
        echo $i
        echo 'bad luck from Japan'
        ;;

    17) echo $i
        echo 'bad luck from Italy'
        ;;

    *) echo $i
       ;;

    esac

    i=`expr $i + 1`
done
