#!/usr/bin/env bash
# printing numbers 1-20 exvept on 4th, 9th and 17th iterations 
i=1
while [ $i -le 20 ]
do
    i=`expr $i + 1;
    case $i in
    4) echo 'bad luck from China';;
    6) echo 'bad luck from Japan';;
    17) echo 'bad luck from Italy';;
    *) echo $i;;
    esac
done
